[build]
builder = "nixpacks"
buildCommand = "cd server && mvn clean package spring-boot:repackage -DskipTests"

[deploy]
startCommand = "cd server && java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/Server-1.0-SNAPSHOT.jar"